#define FASTSERIAL_BASE  0x93000000

#define FASTSERIAL_RX_OFFSET          (0)
#define FASTSERIAL_TX_OFFSET          (4)

#define FASTSERIAL_RX_REG *(volatile uint32_t *)(FASTSERIAL_BASE + (FASTSERIAL_RX_OFFSET))
#define FASTSERIAL_TX_REG  *(volatile uint32_t *)(FASTSERIAL_BASE + (FASTSERIAL_TX_OFFSET))


#define FASTSERIAL_STATUS_RX_READY (1<<8)
#define FASTSERIAL_STATUS_TX_FULL  (1<<9)